version: '3.9'

services:

  #postgres-db:
  #  image: postgres
  #  restart: always
  #  environment:
  #    POSTGRES_PASSWORD: P4$$w0rd
  #    POSTGRES_USER: ud_pg
  #    POSTGRES_DB: ud_db_course
  #  ports:
  #    - "5432:5432"
  #  volumes:
  #    - postgres-data:/var/lib/postgresql/data
  #  networks:
  #    - db-network

  mysql-db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_DATABASE: ud_db_course
      MYSQL_USER: mysql_ud
      MYSQL_PASSWORD: P4$$w0rd
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - db-network

  #backend:
  #  build: .
  #  ports:
  #    - "5000:5000"
  #  networks:
  #    - db-network
  #  depends_on:
  #    - postgres-db
  #    - mysql-db
  
networks:
  db-network:
    driver: bridge

volumes:
  #postgres-data:
  #  driver: local
  mysql-data:
    driver: local