version: '3.3'

services:

  postgres-db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ud_admin
      POSTGRES_PASSWORD: Admin12345
      POSTGRES_DB: ud_db_project
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - local

  mysql-db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: P4ssw0rd
      MYSQL_DATABASE: ud_db_project
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - local
  

volumes:
  postgres-data:
    driver: local
  mysql-data:
    driver: local

networks:
  local:
    driver: bridge
