name: CD

on:
    workflow_dispatch:
        inputs:
            environment:
                description: "Environment to deploy"
                required: True
                type: choice
                options:
                    - test
                    - prod

jobs:
    test:
        name: RunTestHighLevel
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.13'

            - name: Run IntegrationTests
              run: |
                cucumber run integrationTests

            - name: Run StressTests
              run: |
                jmeter run stressTest
            
            - name: Run IntegrationTests
              run: |
                cucumber run acceptationTests
            
    deploy-test:
        name: Deploy2Test
        needs: test
        if: inputs.environment == 'test'
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Credentials
          uses: cloud-actions/configure-provider
          with:
            id-account: ${{ secrets.CLOUD_ACCOUNT_TEST }}
            user: ${{ secrets.CLOUD_USER_TEST }}
            password: ${{ secrets.CLOUD_PASSWORD_TEST }}
          
        - name: Build Docker Image
          run: |
            docker build -t my_app:${{ github.sha }} .
          
        - name: Push Docker Image to CloudProvider
          run: |
            docker push my_app:${{ github.sha }}
  
        - name: Deploy to CloudProvider
          run: |
              cloud-compute-service run my-app-test \
                --image my_app:${{ github.sha }} \
      

    deploy-prod:
        name: Deploy2Test
        needs: test
        if: inputs.environment == 'prod'
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v4

        - name: Setup Credentials
          uses: cloud-actions/configure-provider
          with:
            id-account: ${{ secrets.CLOUD_ACCOUNT_PROD }}
            user: ${{ secrets.CLOUD_USER_PROD }}
            password: ${{ secrets.CLOUD_PASSWORD_PROD }}
          
        - name: Build Docker Image
          run: |
            docker build -t my_app:${{ github.sha }} .
          
        - name: Push Docker Image to CloudProvider
          run: |
            docker push my_app:${{ github.sha }}
  
        - name: Deploy to CloudProvider
          run: |
              cloud-compute-service run my-app-prod \
                --image my_app:${{ github.sha }} \
      